# Generated by Django 3.2.4 on 2021-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('stop_id', models.CharField(max_length=50, verbose_name='stop_id')),
                ('stop_sequence', models.IntegerField(verbose_name='stop_sequence')),
                ('destination', models.CharField(max_length=100, verbose_name='destination')),
                ('stop_name', models.CharField(max_length=100, verbose_name='stop_name')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('ainm', models.CharField(max_length=100, verbose_name='ainm')),
                ('route_num', models.CharField(max_length=20, verbose_name='route_num')),
            ],
        ),
    ]
