# Generated by Django 3.2.4 on 2021-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='shape_id',
            field=models.CharField(default=0, max_length=100, verbose_name='shape_id'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='trip_id',
            field=models.CharField(default=0, max_length=100, verbose_name='trip_id'),
        ),
    ]
