# Generated by Django 3.2.4 on 2021-07-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routes', '0002_auto_20210710_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='stop_num',
            field=models.CharField(default=0, max_length=20, verbose_name='stop_num'),
        ),
    ]
